### ISSUE TITLE
Animation stop when using KeyboardObserving

### ISSUE THREAD

**Issue by harismawan** [nickffox/KeyboardObserving#12]
Animation not working when using KeyboardObserving, after removing it animation work as expected.

**Comment by omroz** [comment]
@AFHarismawan you can try my pending pull-request #13 , I think it will resolve your issue.

**Comment by nickffox** [comment]
@AFHarismawan do you have a code snippet you can share demonstrating the issue?

What version of Xcode are you using, and what version of iOS are you seeing the problem on?

**Comment by harismawan** [comment]
> @AFHarismawan you can try my pending pull-request #13 , I think it will resolve your issue.

I think @omroz fix my issue
thanks
