### ISSUE TITLE
Manually observe for keyboard?

### ISSUE THREAD

**Issue by mroushdy** [nickffox/KeyboardObserving#17]
How do I manually observe for keyboard changes in a swiftUi view? to: fade in and out things etc.

**Comment by nickffox** [comment]
For this use case, you probably want to subscribe to the `Keyboard` type's `state` property.

As this is a published property, you can access the backing `Publisher<Keyboard.State, Never>` using `$state`.

@mroushdy Will this help you address your issue?

**Comment by mroushdy** [comment]
this is perfect! Thank you
