### ISSUE TITLE
Fatal Error when using KeyboardObservingView

### ISSUE THREAD

**Issue by BatuhanGnday** [nickffox/KeyboardObserving#21]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/32869414/83952594-86bc0b80-a842-11ea-90bd-9e75ffd291b1.png">

**Comment by nickffox** [comment]
Hey @BatuhanGnday it looks like there isn’t a `Keyboard` instance in the environment. Make sure you’ve added that in your `SceneDelegate` (or wherever you set up you’re environment).

Here’s the link to the documentation showing [how to do this](https://github.com/nickffox/KeyboardObserving#1-add-a-keyboard-to-your-environment).

**Comment by BatuhanGnday** [comment]
I missed that point when I was reading README. This is my fault obviously. Thank you for your interest @nickffox. I fixed the problem. Thanks again.

**Comment by nickffox** [comment]
@BatuhanGnday no problem! I’ll close this issue.
